import pygame
import random

pygame.init()

# Configurações do jogo
largura, altura = 300, 600
tamanho_bloco = 30
velocidade_jogo = 500
cores = [(0, 0, 0), (255, 0, 0), (0, 255, 0), (0, 0, 255), (255, 255, 0)]

# Definição das peças
peças = [
    [[1, 1, 1, 1]],
    [[1, 1, 1], [1]],
    [[1, 1, 1], [0, 0, 1]],
    [[1, 1, 1], [0, 1]],
    [[1, 1], [1, 1]],
    [[1, 1, 0], [0, 1, 1]]
]

# Função para criar uma nova peça
def nova_peça():
    return random.choice(peças)

# Inicialização da tela
tela = pygame.display.set_mode((largura, altura))
pygame.display.set_caption("Tetris")

# Loop principal do jogo
while True:
    for evento in pygame.event.get():
        if evento.type == pygame.QUIT:
            pygame.quit()
            exit()

    # Lógica do jogo aqui

    pygame.time.delay(velocidade_jogo)
    pygame.display.update()
